project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: assets/images/sCellgen_icon.ico
  navbar:
    logo: assets/images/sCellgen_logo.svg
    background: primary
    left:
      - text: "Workflow"
        file: documentation/workflow.qmd
      - text: "Module Documentation"
        file: documentation/modules.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
    code-fold: true
    highlight-style: breeze
    css: assets/css/styles.css